version: '3'
services:

  subscribers_db:
    container_name:  postgres-subs-db
    image:           postgres
    ports:
      - 5434:5432
    restart: always
    volumes:
      - ../db-data:/var/lib/postgresql/data
    env_file: ../.env
    environment:
      - LC_ALL=C.UTF-8

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080